const groups=['國小動畫 AI 互動組','國小遊戲 AI 互動組','國中生活 AI 互動組','國中 AI 智慧生活組'];
const descriptions=['故事敘事、動畫表現與 AI 互動體驗','遊戲設計、操作體驗與 AI 互動機制','生活議題、解決構想與 AI 互動應用','智慧生活情境、AI 應用與實用價值'];
const names=['創意與主題表現','程式設計與功能','AI 應用與互動','作品完整度與使用體驗','作品說明與展示'];
const $=id=>document.getElementById(id);let selected=null,view='choose',records=[],weights=[25,25,25,15,10],activeWeights;
try{records=JSON.parse(localStorage.getItem('scratchScores')||'[]');if(!Array.isArray(records))records=[];const w=JSON.parse(localStorage.getItem('scratchWeights')||'null');if(w&&w.length===5&&w.every(n=>Number.isInteger(n)&&n>=0)&&w.reduce((a,b)=>a+b,0)===100)weights=w}catch{records=[]}
function notice(t){$('message').textContent=t;$('message').classList.remove('hidden')}
function show(v){view=v;for(const x of ['choose','scoring','history'])$(x).classList.toggle('hidden',x!==v);$('settings').classList.toggle('hidden',v!=='choose');$('step1').classList.toggle('active',v==='choose');$('step2').classList.toggle('active',v==='scoring');$('message').classList.add('hidden');window.scrollTo(0,0)}
groups.forEach((g,i)=>{const b=document.createElement('button');b.className='card';b.setAttribute('aria-pressed','false');b.innerHTML=`<span class="icon">${['✦','♟','⌂','◈'][i]}</span><h2>${i+1}. ${g}</h2><p>${descriptions[i]}</p>`;b.onclick=()=>{selected=i;document.querySelectorAll('.card').forEach((c,j)=>{c.classList.toggle('selected',j===i);c.setAttribute('aria-pressed',j===i?'true':'false')});$('selection').textContent='已選擇：'+g;$('start').disabled=false};$('groups').append(b)});
function begin(){activeWeights=[...weights];$('groupTitle').textContent=groups[selected];$('criteria').replaceChildren();names.forEach((name,i)=>{const row=document.createElement('div');row.className='criterion';row.innerHTML=`<div><label for="score${i}">${name} <span class="muted">／ ${activeWeights[i]} 分</span></label><p>${[descriptions[selected],'程式邏輯清楚、功能正常，能處理操作中的狀況','AI 的運用有明確目的，與使用者互動自然且有意義','作品完成度、介面清晰度與整體操作流暢性','能說明設計想法、程式原理與 AI 使用方式'][i]}</p></div><input id="score${i}" aria-label="${name}分數" type="number" min="0" max="${activeWeights[i]}" step="1" required placeholder="0–${activeWeights[i]}">`;$('criteria').append(row);$('score'+i).oninput=updateTotal});updateTotal();show('scoring')}
function updateTotal(){$('total').textContent=names.reduce((s,_,i)=>s+(Number($('score'+i).value)||0),0)}
$('start').onclick=begin;$('back').onclick=()=>{if([...$('form').elements].some(e=>e.id!=='judge'&&e.value)&&!confirm('返回選組會清除這次尚未儲存的作品與分數，是否繼續？'))return;const judge=$('judge').value;$('form').reset();$('judge').value=judge;show('choose')};
$('form').onsubmit=e=>{e.preventDefault();if(!['judge','entry','title'].every(id=>$(id).value.trim())){notice('請填寫評分者、作品編號與作品名稱。');return}const scores=names.map((_,i)=>Number($('score'+i).value));if(!scores.every((n,i)=>Number.isInteger(n)&&n>=0&&n<=activeWeights[i]))return;const r={group:groups[selected],judge:$('judge').value.trim(),entry:$('entry').value.trim(),title:$('title').value.trim(),url:$('url').value,feedback:$('feedback').value,scores,weights:[...activeWeights],total:scores.reduce((a,b)=>a+b,0),time:new Date().toISOString()};try{localStorage.setItem('scratchScores',JSON.stringify([...records,r]))}catch{notice('瀏覽器無法儲存，請保留表單並確認儲存空間或瀏覽器設定。');return}records.push(r);$('count').textContent=records.length;const judge=r.judge;$('form').reset();$('judge').value=judge;begin();notice(`已儲存「${r.title}」，總分 ${r.total} 分。可繼續評下一件作品。`)};
$('count').textContent=records.length;$('filter').innerHTML='<option value="">全部組別</option>';groups.forEach(g=>{const o=document.createElement('option');o.value=g;o.textContent=g;$('filter').append(o)});let previous='choose';$('historyBtn').onclick=()=>{if(view!=='history')previous=view;show('history');renderRecords()};$('closeHistory').onclick=()=>show(previous);$('filter').onchange=renderRecords;
function filtered(){return records.filter(r=>!$('filter').value||r.group===$('filter').value)}
function renderRecords(){$('records').replaceChildren();const rs=filtered();$('empty').classList.toggle('hidden',rs.length>0);rs.slice().reverse().forEach(r=>{const tr=document.createElement('tr');[r.group,r.entry+' · '+r.title,r.judge,r.total+' / 100',new Date(r.time).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})].forEach(x=>{const td=document.createElement('td');td.textContent=x;tr.append(td)});$('records').append(tr)});$('export').disabled=!rs.length}
$('export').onclick=()=>{const safe=x=>'"'+String(x??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const rows=[['組別','作品編號／隊伍','作品名稱','評分者',...names,...names.map(n=>n+'滿分'),'總分','評語','作品連結','時間（台北）'],...filtered().map(r=>[r.group,r.entry,r.title,r.judge,...r.scores,...r.weights,r.total,r.feedback,r.url,new Date(r.time).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})])];const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Scratch評分紀錄.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
names.forEach((n,i)=>{const d=document.createElement('div');d.innerHTML=`<label for="w${i}">${n}</label><input id="w${i}" type="number" min="0" max="100" step="1" value="${weights[i]}">`;$('weights').append(d);$('w'+i).oninput=weightSum});function weightSum(){$('weightTotal').textContent='合計：'+names.reduce((s,_,i)=>s+Number($('w'+i).value),0)+' / 100 分'}weightSum();$('saveWeights').onclick=()=>{const w=names.map((_,i)=>Number($('w'+i).value));if(!w.every((n,i)=>$('w'+i).value!==''&&Number.isInteger(n)&&n>=0&&n<=100)||w.reduce((a,b)=>a+b,0)!==100){notice('各項配分須為非負整數，合計必須為 100 分。');return}try{localStorage.setItem('scratchWeights',JSON.stringify(w));weights=w;notice('配分已儲存，將套用到下一份評分。')}catch{notice('瀏覽器無法儲存配分。')}};
