// 學生互評：每份紀錄保留當時的項目名稱與分數。
const peerRubrics = [
[['片頭介紹','有作品名稱，能知道故事的主題。'],['故事內容','有開始、發展與結局，故事看得懂。'],['角色與對話','角色清楚，對話停留時間足夠。'],['背景與畫面','符合情境，文字和角色看得清楚。'],['動畫動作','角色動作和場景切換順暢。'],['音樂與音效','符合情境，音量適當。'],['互動操作','提示清楚，按鍵或點擊有回應。'],['AI 互動表現','作者說明 AI 用途，實際互動符合說明。'],['片尾與來源','有結尾，標示圖片、音樂等素材來源。'],['執行與創意','能完整播放，有印象深刻的設計。']],
[['開始畫面','有遊戲名稱與開始按鈕。'],['遊戲規則','清楚說明目標、玩法與勝負條件。'],['操作方式','按鍵或滑鼠容易操作。'],['角色與場景','角色、背景與遊戲內容相符。'],['音樂與音效','音效能提示事件，音量適當。'],['互動回應','操作後能立即得到清楚的回應。'],['AI 互動','作者說明 AI 用途，能實際測試。'],['關卡與難度','難度適合，挑戰能逐步增加。'],['計分與結束畫面','分數正確，有勝負結果與重新開始方式。'],['執行順暢度','能完成遊戲，沒有卡住或明顯錯誤。']],
[['主題介紹','能知道作品要處理的生活主題。'],['生活問題說明','清楚說出誰遇到什麼問題。'],['解決方法','方法能回應提出的問題。'],['畫面與文字','文字清楚，畫面容易理解。'],['操作提示','知道要輸入、點擊或按哪個鍵。'],['互動回應','操作後得到清楚、合理的回應。'],['AI 用途說明','作者能說明 AI 幫忙做什麼。'],['AI 實際表現','測試後，AI 回應符合說明的用途。'],['成果與結尾','能看到解決結果，有清楚的結尾。'],['執行順暢度','能完整使用，沒有卡住或明顯錯誤。']],
[['主題介紹','能知道作品的名稱與目的。'],['使用情境','知道誰會在什麼情況下使用。'],['生活實用性','功能對生活問題有具體幫助。'],['操作提示','每一步都有容易理解的提示。'],['資料輸入','能順利輸入或選擇所需資料。'],['結果呈現','結果清楚，知道下一步可以做什麼。'],['AI 用途說明','作者能說明 AI 在作品中的任務。'],['AI 實際表現','測試不同輸入，回應符合任務。'],['錯誤提示與處理','輸入不完整或錯誤時，有提示並能重試。'],['執行順暢度','能完整操作，沒有卡住或明顯錯誤。']]
];
$('settings').remove();
const baseShow=show;show=function(v){view=v;for(const x of ['choose','scoring','history'])$(x).classList.toggle('hidden',x!==v);$('step1').classList.toggle('active',v==='choose');$('step2').classList.toggle('active',v==='scoring');$('message').classList.add('hidden');window.scrollTo(0,0)};
$('feedback').parentElement.innerHTML='<label for="praise">我最喜歡的地方是……因為……（選填）</label><textarea id="praise" maxlength="1000" placeholder="指出一個具體亮點，說明原因。"></textarea><label for="suggestion">我建議改進……可以試著……（選填）</label><textarea id="suggestion" maxlength="1000" placeholder="提出一個具體、做得到的建議。"></textarea>';
begin=function(){activeWeights=Array(10).fill(10);$('groupTitle').textContent=groups[selected];$('criteria').replaceChildren();const guide=document.createElement('p');guide.textContent='0：沒有或無法使用 · 2：不清楚或常出錯 · 5：基本完成 · 8：清楚順暢 · 10：完整且有巧思。請先完整試用，再依提示評分；這是學生互評建議，並非官方競賽規準。';$('criteria').append(guide);peerRubrics[selected].forEach(([name,hint],i)=>{const row=document.createElement('div');row.className='criterion';row.innerHTML=`<div><label for="score${i}">${i+1}. ${name} <span class="muted">／10 分</span></label><p>${hint}</p></div><select id="score${i}" aria-label="${name}分數" required><option value="">請選分數</option>${[0,2,5,8,10].map(n=>`<option value="${n}">${n} 分</option>`).join('')}</select>`;$('criteria').append(row);$('score'+i).onchange=updateTotal});updateTotal();show('scoring')};
updateTotal=function(){$('total').textContent=Array.from({length:10},(_,i)=>Number($('score'+i).value)||0).reduce((a,b)=>a+b,0)};
$('start').onclick=begin;
$('form').onsubmit=e=>{e.preventDefault();if(!$('form').reportValidity())return;const scores=Array.from({length:10},(_,i)=>Number($('score'+i).value));const r={rubricVersion:'peer-v1',criteria:peerRubrics[selected].map(x=>x[0]),group:groups[selected],judge:$('judge').value.trim(),entry:$('entry').value.trim(),title:$('title').value.trim(),url:$('url').value,feedback:'我最喜歡：'+$('praise').value+'\n我建議：'+$('suggestion').value,scores,weights:Array(10).fill(10),total:scores.reduce((a,b)=>a+b,0),time:new Date().toISOString()};if(!r.judge||!r.entry||!r.title){notice('請填寫評分者、作品編號與作品名稱。');return}try{localStorage.setItem('scratchScores',JSON.stringify([...records,r]))}catch{notice('瀏覽器無法儲存，請保留表單。');return}records.push(r);$('count').textContent=records.length;$('form').reset();$('judge').value=r.judge;begin();notice(`已儲存「${r.title}」，總分 ${r.total} 分。`)};
$('export').onclick=()=>{const safe=x=>'"'+String(x??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const rows=[['組別','作品編號','作品名稱','評分者','項目','分數','滿分','總分','回饋','作品連結','評分時間'],...filtered().flatMap(r=>r.scores.map((s,i)=>[r.group,r.entry,r.title,r.judge,(r.criteria||names)[i],s,r.weights[i],r.total,r.feedback,r.url,r.time]))];const link=document.createElement('a');link.href=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));link.download='學生互評紀錄.csv';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)};
