let sheetEndpoint=localStorage.getItem('scratchSheetEndpoint')||'',sheetCode='',sheetConnected=false;
const panel=document.createElement('section');panel.className='panel';panel.innerHTML='<h2>Google 試算表連線</h2><p id="sheetStatus">尚未連線：完成設定後，每次儲存評分會自動送出。</p><p><a href="https://docs.google.com/spreadsheets/d/YOUR_SPREADSHEET_ID/edit" target="_blank" rel="noopener">開啟成績試算表</a> · <a href="sheets-setup.html" target="_blank" rel="noopener">首次設定說明與程式碼</a></p><div class="fields"><div><label for="sheetEndpoint">Apps Script 部署網址</label><input id="sheetEndpoint" type="url" placeholder="https://script.google.com/macros/s/…/exec"></div><div><label for="sheetCode">評分通行碼</label><input id="sheetCode" type="password" autocomplete="off" placeholder="向試算表擁有者取得"></div></div><div class="bar"><span class="muted">通行碼只用於本次頁面，不儲存在瀏覽器。</span><button id="connectSheet" class="secondary">確認連線</button></div>';
document.querySelector('main').insertBefore(panel,$('choose'));$('sheetEndpoint').value=sheetEndpoint;
const syncBtn=document.createElement('button');syncBtn.className='secondary';syncBtn.textContent='同步尚未確認的成績';$('history').append(syncBtn);
function setSheetStatus(t){$('sheetStatus').textContent=t}
function validEndpoint(s){return /^https:\/\/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]+\/exec$/.test(s)}
function sheetRequest(action,record){return new Promise((resolve,reject)=>{
  const requestId=crypto.randomUUID();const frame=document.createElement('iframe');frame.name='sheet-'+requestId;frame.hidden=true;
  const form=document.createElement('form');form.method='POST';form.action=sheetEndpoint;form.target=frame.name;form.hidden=true;
  const input=document.createElement('input');input.name='payload';input.value=JSON.stringify({action,record,requestId,code:sheetCode,origin:location.origin});form.append(input);
  const cleanup=()=>{clearTimeout(timer);window.removeEventListener('message',receive);form.remove();frame.remove()};
  const receive=e=>{let host;try{host=new URL(e.origin).hostname}catch{return}if(e.origin!=='https://script.google.com'&&!(e.origin.startsWith('https://')&&(host==='script.googleusercontent.com'||host.endsWith('.script.googleusercontent.com')||host.endsWith('-script.googleusercontent.com'))))return;const d=e.data;if(!d||d.type!=='scratch-sheet-result'||d.requestId!==requestId)return;cleanup();d.ok?resolve(d):reject(Error(d.message||'寫入失敗'))};
  const timer=setTimeout(()=>{cleanup();reject(Error('尚未收到 Google 寫入確認；請確認部署設定並重試。'))},45000);
  window.addEventListener('message',receive);document.body.append(frame,form);form.submit();
})}
$('connectSheet').onclick=async()=>{const endpoint=$('sheetEndpoint').value.trim(),code=$('sheetCode').value.trim();if(!validEndpoint(endpoint)||!code){setSheetStatus('請填寫正確的 /exec 部署網址與評分通行碼。');return}sheetEndpoint=endpoint;sheetCode=code;sheetConnected=false;$('connectSheet').disabled=true;setSheetStatus('正在確認連線…');try{await sheetRequest('check');sheetConnected=true;try{localStorage.setItem('scratchSheetEndpoint',endpoint)}catch{}setSheetStatus('已連線：之後每次儲存評分將自動寫入 Google 試算表。')}catch(e){setSheetStatus('連線失敗：'+e.message)}finally{$('connectSheet').disabled=false}};
function persistRecords(){localStorage.setItem('scratchScores',JSON.stringify(records))}
async function sendRecord(r){if(!sheetConnected){setSheetStatus('本機已儲存，Google 尚未連線。請確認連線後同步未確認的成績。');return}setSheetStatus('成績傳送中…');try{await sheetRequest('score',r);r.sheetSynced=true;r.sheetTarget=sheetEndpoint;persistRecords();setSheetStatus('「'+r.title+'」已確認寫入 Google 試算表。')}catch(e){setSheetStatus('「'+r.title+'」本機已保留，Google 尚未確認：'+e.message)}}
syncBtn.onclick=async()=>{if(!sheetConnected){setSheetStatus('請先完成 Google 試算表連線。');panel.scrollIntoView({behavior:'smooth'});return}syncBtn.disabled=true;try{for(const r of records.filter(r=>!r.sheetSynced||r.sheetTarget!==sheetEndpoint)){if(!r.id){r.id=crypto.randomUUID();persistRecords()}await sendRecord(r);if(!r.sheetSynced||r.sheetTarget!==sheetEndpoint)break}if(records.every(r=>r.sheetSynced&&r.sheetTarget===sheetEndpoint))setSheetStatus('所有本機成績皆已確認寫入 Google 試算表。')}finally{syncBtn.disabled=false}};
const originalSubmit=$('form').onsubmit;$('form').onsubmit=async e=>{const before=records.length;originalSubmit(e);if(records.length>before){const r=records[records.length-1];r.id=crypto.randomUUID();try{persistRecords()}catch{setSheetStatus('本機儲存發生問題，請先匯出成績備份。');return}await sendRecord(r)}};

